import type { CSSProperties } from "react";

export const designTokens = {
  color: {
    bg: "#faf7f2",
    surface: "#f0e8dc",
    surfaceDeep: "#e8d9c4",
    surfaceCard: "#fffdf9",
    charcoal: "#2c2c2a",
    charcoalMid: "#4a4a47",
    muted: "#8a7f72",
    subtle: "#b5aa9e",
    accent: "#c45c2e",
    accentSoft: "#f5ede6",
    cognac: "#9b6a3e",
    border: "rgba(155, 106, 62, 0.18)",
    heroGlowPrimary: "rgba(196, 92, 46, 0.09)",
    heroGlowSecondary: "rgba(155, 106, 62, 0.08)",
    whiteWarm: "#fcfaf6",
    whiteAccent: "#f7f0e7",
    whitePure: "rgba(255, 255, 255, 0.72)",
    whiteSoft: "rgba(255, 255, 255, 0.82)",
    whiteDense: "rgba(250, 247, 242, 0.9)",
    whiteOverlay: "rgba(250, 247, 242, 0.92)",
  },
  shadow: {
    soft: "0 24px 64px rgba(82, 57, 34, 0.08)",
    card: "0 18px 40px rgba(72, 54, 39, 0.1)",
    floating: "0 12px 30px rgba(92, 67, 42, 0.08)",
    hero: "0 30px 90px rgba(79, 56, 33, 0.14)",
  },
  radius: {
    sm: "6px",
    md: "10px",
    lg: "16px",
    xl: "24px",
    pill: "999px",
  },
  layout: {
    shell: "1120px",
    heroShell: "1080px",
  },
  typography: {
    family: {
      body: "var(--font-body), sans-serif",
      display: "var(--font-display), sans-serif",
    },
    weight: {
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    size: {
      label: "0.7rem",
      nav: "0.78rem",
      body: "1rem",
      bodyLarge: "clamp(0.98rem, 1.15vw, 1.08rem)",
      pretitle: "clamp(1.1rem, 2vw, 1.4rem)",
      sectionTitle: "clamp(2.3rem, 5vw, 4.4rem)",
      heroTitle: "clamp(2.9rem, min(7vw, 11dvh), 7.4rem)",
      cardTitle: "1.45rem",
      experienceTitle: "clamp(1.65rem, 2.5vw, 2.2rem)",
      projectDisplay: "clamp(2rem, 4vw, 3rem)",
    },
    lineHeight: {
      tight: "0.88",
      heading: "0.95",
      compact: "1",
      body: "1.8",
      bodyRelaxed: "clamp(1.6, 1.9dvh, 1.8)",
      label: "1.05",
    },
    tracking: {
      label: "0.14em",
      nav: "0.08em",
      button: "0.1em",
      display: "-0.03em",
      section: "-0.02em",
      displayWide: "0.05em",
    },
  },
  motion: {
    revealDuration: "0.72s",
    revealEase: "cubic-bezier(0.22, 1, 0.36, 1)",
    transitionFast: "160ms ease",
    transitionMedium: "180ms ease",
  },
} as const;

export const designSystemRootVariables: CSSProperties = {
  "--bg": designTokens.color.bg,
  "--surface": designTokens.color.surface,
  "--surface-deep": designTokens.color.surfaceDeep,
  "--surface-card": designTokens.color.surfaceCard,
  "--charcoal": designTokens.color.charcoal,
  "--charcoal-mid": designTokens.color.charcoalMid,
  "--muted": designTokens.color.muted,
  "--subtle": designTokens.color.subtle,
  "--accent": designTokens.color.accent,
  "--accent-soft": designTokens.color.accentSoft,
  "--cognac": designTokens.color.cognac,
  "--border": designTokens.color.border,
  "--hero-glow-primary": designTokens.color.heroGlowPrimary,
  "--hero-glow-secondary": designTokens.color.heroGlowSecondary,
  "--white-warm": designTokens.color.whiteWarm,
  "--white-accent": designTokens.color.whiteAccent,
  "--white-pure": designTokens.color.whitePure,
  "--white-soft": designTokens.color.whiteSoft,
  "--white-dense": designTokens.color.whiteDense,
  "--white-overlay": designTokens.color.whiteOverlay,
  "--shadow-soft": designTokens.shadow.soft,
  "--shadow-card": designTokens.shadow.card,
  "--shadow-floating": designTokens.shadow.floating,
  "--shadow-hero": designTokens.shadow.hero,
  "--radius-sm": designTokens.radius.sm,
  "--radius-md": designTokens.radius.md,
  "--radius-lg": designTokens.radius.lg,
  "--radius-xl": designTokens.radius.xl,
  "--radius-pill": designTokens.radius.pill,
  "--shell": designTokens.layout.shell,
  "--hero-shell": designTokens.layout.heroShell,
  "--font-family-body": designTokens.typography.family.body,
  "--font-family-display": designTokens.typography.family.display,
  "--font-weight-medium": designTokens.typography.weight.medium,
  "--font-weight-semibold": designTokens.typography.weight.semibold,
  "--font-weight-bold": designTokens.typography.weight.bold,
  "--font-size-label": designTokens.typography.size.label,
  "--font-size-nav": designTokens.typography.size.nav,
  "--font-size-body": designTokens.typography.size.body,
  "--font-size-body-large": designTokens.typography.size.bodyLarge,
  "--font-size-pretitle": designTokens.typography.size.pretitle,
  "--font-size-section-title": designTokens.typography.size.sectionTitle,
  "--font-size-hero-title": designTokens.typography.size.heroTitle,
  "--font-size-card-title": designTokens.typography.size.cardTitle,
  "--font-size-experience-title": designTokens.typography.size.experienceTitle,
  "--font-size-project-display": designTokens.typography.size.projectDisplay,
  "--line-height-tight": designTokens.typography.lineHeight.tight,
  "--line-height-heading": designTokens.typography.lineHeight.heading,
  "--line-height-compact": designTokens.typography.lineHeight.compact,
  "--line-height-body": designTokens.typography.lineHeight.body,
  "--line-height-body-relaxed": designTokens.typography.lineHeight.bodyRelaxed,
  "--line-height-label": designTokens.typography.lineHeight.label,
  "--tracking-label": designTokens.typography.tracking.label,
  "--tracking-nav": designTokens.typography.tracking.nav,
  "--tracking-button": designTokens.typography.tracking.button,
  "--tracking-display": designTokens.typography.tracking.display,
  "--tracking-section": designTokens.typography.tracking.section,
  "--tracking-display-wide": designTokens.typography.tracking.displayWide,
  "--motion-reveal-duration": designTokens.motion.revealDuration,
  "--motion-reveal-ease": designTokens.motion.revealEase,
  "--motion-fast": designTokens.motion.transitionFast,
  "--motion-medium": designTokens.motion.transitionMedium,
} as CSSProperties;
